services:
  db:
    container_name: docs-management-db
    image: postgres:15.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: docs-management
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password