services:
  db:
    container_name: docs-management-db
    image: postgres:15.6
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_DB: docs-management
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  keycloak:
    container_name: docs-management-keycloak
    image: quay.io/keycloak/keycloak:24.0.3
    ports:
      - ${KEYCLOAK_PORT}:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import
    command: start-dev --import-realm