spring:
  application:
    name: doc-management-api
  datasource:
    url: jdbc:postgresql://localhost:5432/docs-management
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/doc-management
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
logging:
  level:
    org.jooq.tools.LoggerListener: DEBUG

keycloak:
  admin:
    server-url: ${KEYCLOAK_ADMIN_URL:http://localhost:8090/}
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
    realm: ${KEYCLOAK_ADMIN_REALM:master}
    username: ${KEYCLOAK_ADMIN_USERNAME:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
    grant-type: ${KEYCLOAK_ADMIN_GRANT_TYPE:password}
